name: Playwright Tests with docker

on:
  workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  playwright-test-docker:
    name: 'Playwright Tests Docker'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.0-jammy
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
    
      - name: Install dependencies
        run: npm ci
    
      - name: Run your tests
        run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: index.html
        path: playwright-report/index.html
        retention-days: 30